name: nathan_app
description: A new Flutter project.

version: 1.0.9+9

environment:
  sdk: '>=2.19.2 <3.10.6'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.0.1
  font_awesome_flutter: ^10.4.0
  fluttericon: ^2.0.0
  flag: ^7.0.0
  dio: ^5.4.0
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  pull_to_refresh: ^2.0.0
  intl_phone_field: ^3.1.0
  country_code_picker: ^3.0.0
  image_picker: ^1.0.1
  uuid: ^4.2.1
  mime: ^1.0.2
  flutter_spinkit: ^5.1.0
  flutter_launcher_icons: ^0.13.0
  percent_indicator: ^4.2.3
  http: ^0.13.4
  flutter_staggered_grid_view: ^0.7.0
  retrofit: ^4.0.1
  retrofit_generator: ^8.0.4
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  dots_indicator: ^3.0.0
  responsive_sizer: ^3.3.0+1
  rabbit_converter: ^2.0.0
  flutter_mdetect: ^0.0.4
  flutter_localizations:
    sdk: flutter
  intl: any
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_app_version_checker: ^0.3.2
  url_launcher: ^6.2.5
  device_info_plus: ^3.2.3
  marquee: ^2.2.3
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  awesome_notifications: any
  auto_size_text: ^3.0.0
  web: ^0.3.0  
  firebase_core_web: ^2.11.5
  shared_preferences_web: ^2.2.2
  google_mobile_ads: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.jpeg"
  remove_alpha_ios: true
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
assets:
  - images/
  - assets/svg/
  - assets/

